[project]
name = "python-physics"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pydantic==2.12.5",
    "pygame>=2.6.1",
    "ruff>=0.14.13",
]
